[package]
name = "bsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.6"
base16ct = "0.2.0"
hex-literal = "0.3"
generic-array = "0.14.6"
